INSERT INTO department (name)
VALUES
    ('Sales'),
    ('Finance'),
    ('Legal'),
    ('Engineering');

INSERT INTO role (title, salary, department_id)
VALUES
    ('Sales Lead', 40000, 1),
    ('Sales Associate', 25000, 1),
    ('Phone Operator', 30000, 1),
    ('Banker', 50000, 2),
    ('Accountant', 65000, 2),
    ('Loan Specialist', 70000, 2),
    ('Lawyer', 190000, 3),
    ('Legal Team Lead', 250000, 3),
    ('Paralegal', 35000, 3),
    ('Software Engineer', 120000, 4),
    ('Electrical Engineer', 80000, 4),
    ('Computer Vision Engineer', 95000, 4);

-- INSERT INTO manager (first_name, last_name)
-- VALUES
--     ('Vitorio', 'DeSica'),
--     ('Wilkie', 'Collins'),
--     ('Elizabeth', 'Gaskell'),
--     ('George', 'Sand'),
--     ('Vernon', 'Lee'),
--     ('Arthur', 'Machen'),
--     ('Frederick', 'Marryat'),
--     ('Harriet', 'Martineau'),
--     ('George', 'Meredith'),
--     ('Margaret', 'Oliphant'),
--     ('Anthony', 'Trollope'),
--     ('Charlotte', 'Yonge');

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES
    ('Ronald', 'Firbank', 1, 1),
    ('Virginia', 'Woolf', 1, 1),
    ('Piers', 'Gaveston', 1, 1),
    ('Vitorio', 'DeSica', 1, null),
    ('Charles', 'LeRio', 2, 2),
    ('Katherine', 'Mansfield', 2, 2),
    ('Dora', 'Carrington', 2, 2),
    ('Wilkie', 'Collins', 2, null),
    ('Edward', 'Bellamy', 3, 3),
    ('Montague', 'Summers', 3, 3),
    ('Octavia', 'Butler', 3, 3),
    ('Elizabeth', 'Gaskell', 3, null),
    ('Unica', 'Zurn', 4, 4),
    ('James', 'Fraser', 4, 4),
    ('Jack', 'London', 4, 4),
    ('George', 'Sand', 4, null),
    ('Robert', 'Bruce', 5, 5),
    ('Peter', 'Greenaway', 5, 5),
    ('Derek', 'Jarman', 5, 5),
    ('Vernon', 'Lee', 5, null),
    ('Paolo', 'Pasolini', 6, 6),
    ('Heathcote', 'Williams', 6, 6),
    ('Sandy', 'Powell', 6, 6),
    ('Arthur', 'Machen', 6, null),
    ('Emil', 'Zola', 7, 7),
    ('Sissy', 'Coalpits', 7, 7),
    ('Antoinette', 'Capet', 7, 7),
    ('Frederick', 'Marryat', 7, null),
    ('Samuel', 'Delany', 8, 8),
    ('Tony', 'Duvert', 8, 8),
    ('Dennis', 'Cooper', 8, 8),
    ('Harriet', 'Martineau', 8, null),
    ('Monica', 'Bellucci', 9, 9),
    ('John', 'Dryden', 9, 9),
    ('Alexander', 'Pope', 9, 9),
    ('George', 'Meredith', 9, null),
    ('Lionel', 'Johnson', 10, 10),
    ('Aubrey', 'Beardsley', 10, 10),
    ('Tulse', 'Luper', 10, 10),
    ('Margaret', 'Oliphant', 10, null),
    ('William', 'Morris', 11, 11),
    ('George', 'Shaw', 11, 11),
    ('Arnold', 'Bennett', 11, 11),
    ('Anthony', 'Trollope', 11, null),
    ('Algernon', 'Blackwood', 12, 12),
    ('Rhoda', 'Broughton', 12, 12),
    ('Hart', 'Crane', 12, 12),
    ('Charlotte', 'Yonge', 12, null);